// Shared column order, labels and widths for the pricing and grade workspaces.
export const pricingColumnWidths = [112,126,420,112,96,128,116,92,148,132,150,104,92,154,168,116,104,92,104,92,100,120,120,94,94,94,132,156,180,150,180,148,148,110,150,120,120,132,160,220,160,160,220,190,120];
export const pricingColumnCodes = ['A','E','F','T','U','H','I','W','X','Y','Z','AA','AB','AB-TM补','AB-TM补后','AC','AF','AG','AI','AT','AW','AW物差','AW到手差','AO','AP','AQ','AR','AY','AY说明','AZ','AZ提醒','BA','BB','BF','BE','BE物差','BE到手差','BE说明','BG','BG-TM补','BH','BI','BJ','BJ-ZZ','BK'];
export const pricingColumnKeys = ['newSeries','oldModel','ppv','skuId','levelId','quoteVolume','soldVolume','jdPrice','ahsInput','ahsQuotedPrice','jdSubsidy','jdHandPrice','tmPrice','tmRecyclerSubsidy','tmRecyclerQuotedPrice','tmSubsidyManual','tmHandPrice','zzPrice','zzHandPrice','basePrice','preMarginalProfit','preItemGap','preHandGap','tmItemWin','tmHandWin','zzItemWin','ahsZzHandWin','recommendJdPrice','pricingRemark','recommendAdjustment','smallGapOpportunityRemark','ahsSubsidyAfter','postAhsPrice','postJdHandPrice','postMarginalProfit','postItemGap','postHandGap','marginRemark','postTmItemWin','postAhsTmRecyclerWin','postTmHandWin','postZzItemWin','postAhsZzHandWin','postJdZzHandWin','brand'];
export function pricingColumnLabels(isSelfOperated = false) {
  return ['新机系列','旧机型号','ppv','商品SKUID','等级id',isSelfOperated?'ppv近30天报价访客数':'ppv近30天报价量','ppv近30天成交量','jd裸机价',isSelfOperated?'自营普发券AHS补贴':'对应新品型号ahs投入',isSelfOperated?'jd裸机价+AHS补贴':'含AHS补贴后报价','对应新品型号jd总投入','jd总到手价','tm裸机价','对应新品型号tm回收商投入','含tm回收商补贴后报价','tm总补贴-人工','tm总到手价','zz裸机价','zz券后价','基准价','追前边际利润率','追前tm物品价差','追前tm到手价差','裸机比tm','到手比tm','裸机比zz','仅含ahs补贴+裸机 vs zz到手','京东物品价-追价后','京东物品价-追价后理由','京东物品价-追价后调整金额','小差额提醒',isSelfOperated?'追后AHS补贴':'ahs承担补贴-追价后',isSelfOperated?'追后物品价+AHS补贴':'含AHS补贴后报价-追价后','jd总到手价-追价后','追后边际利润率','追后tm物品价差','追后tm到手价差','追后边际利润率说明','京东物品价-追价后 vs 天猫','京东物品价+ahs补贴-追价后 vs天猫','京东到手价-追价后 vs 天猫','京东物品价-追价后 vs 转转','京东物品价+ahs补贴-追价后 vs 转转','京东到手价-追价后vs转转','品牌名称'];
}
export const pricingPercentKeys = new Set(['preMarginalProfit','postMarginalProfit']);
export const pricingBooleanKeys = new Set(['tmItemWin','tmHandWin','zzItemWin','ahsZzHandWin','postTmItemWin','postAhsTmRecyclerWin','postTmHandWin','postZzItemWin','postAhsZzHandWin','postJdZzHandWin']);
